
from boot import *
import time

def main(name, des):
	txt = load(name)
	txt = txt.replace('\r\n', '\n')
	lines = txt.split('\n')
	cdefines = []
	for line in lines:
		if len(line) == 0:continue
		if line[0].isupper():
			defines = line.split('=')
			if len(defines) != 2: continue
			defines[0] = defines[0].strip()
			defines[1] = defines[1].strip()
			cdefines.append( defines )
	for line in enumerate(cdefines):
		print(line)
	txt = '''/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date ''' + str(time.asctime())+'''
*/
#ifndef INSTRUCTION_H
#define INSTRUCTION_H
'''
	for line in cdefines:
		txt += '#define '+ str( line[0] ) + ' ' + str(line[1]) + '\n'
	txt += '#endif'
	save( des, txt)


if __name__ == '__main__':
	if len(argv) == 3:
		main( argv[1], argv[2])
	else:
		print("usage : src des")