/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date Sat Nov 22 18:18:39 2014
*/
#ifndef INSTRUCTION_H_
#define INSTRUCTION_H_
#define NEW_STRING 1
#define NEW_NUMBER 2
#define ADD 3
#define SUB 4
#define MUL 5
#define DIV 6
#define MOD 7
#define NEG 8
#define NOT 9
#define GT 10
#define LT 11
#define GTEQ 12
#define LTEQ 13
#define EQEQ 14
#define NOTEQ 15
#define IN 16
#define NOTIN 17
#define AND 18
#define OR 19
#define SET 20
#define GET 21
#define STORE_LOCAL 22
#define STORE_GLOBAL 23
#define LOAD_LOCAL 24
#define LOAD_GLOBAL 25
#define LOAD_CONSTANT 26
#define POP 27
#define DICT_SET 28
#define LIST 29
#define DICT 30
#define LIST_APPEND 31
#define LT_JUMP_ON_FALSE 32
#define GT_JUMP_ON_FALSE 33
#define LTEQ_JUMP_ON_FALSE 34
#define GTEQ_JUMP_ON_FALSE 35
#define EQEQ_JUMP_ON_FALSE 36
#define NOTEQ_JUMP_ON_FALSE 37
#define JUMP 38
#define POP_JUMP_ON_FALSE 39
#define POP_JUMP_ON_TRUE 40
#define JUMP_ON_FALSE 41
#define JUMP_ON_TRUE 42
#define TAG 43
#define TAGSIZE 44
#define TM_FOR 45
#define SETJUMP 46
#define UP_JUMP 47
#define CALL 48
#define TM_DEF 49
#define RETURN 50
#define LOAD_PARAMS 51
#define TM_EOF 52
#define TM_EOP 53
#endif