/*
* @author xupingmao<578749341@qq.com>
* @generated by Python
* @date Mon Oct 27 14:59:23 2014
*/
#ifndef INSTRUCTION_H
#define INSTRUCTION_H
#define NEW_STRING 1
#define NEW_NUMBER 2
#define TM_FILE 3
#define ADD 11
#define SUB 12
#define MUL 13
#define DIV 14
#define MOD 15
#define NEG 16
#define NOT 17
#define GT 20
#define LT 21
#define GTEQ 22
#define LTEQ 23
#define EQEQ 24
#define NOTEQ 25
#define IN 26
#define NOTIN 27
#define AND 28
#define OR 29
#define SET 30
#define GET 31
#define STORE_LOCAL 32
#define STORE_GLOBAL 33
#define LOAD_LOCAL 34
#define LOAD_GLOBAL 35
#define POP 36
#define LOAD_CONSTANT 37
#define LIST 40
#define DICT 41
#define LIST_APPEND 42
#define JUMP 50
#define POP_JUMP_ON_FALSE 51
#define POP_JUMP_ON_TRUE 52
#define JUMP_ON_FALSE 53
#define JUMP_ON_TRUE 54
#define TAG 55
#define TAGSIZE 56
#define TM_FOR 57
#define CALL 60
#define TM_DEF 61
#define RETURN 62
#define LOAD_PARAMS 63
#define TM_EOF 64
#define TM_EOP 65
#endif